name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  cd-deploy-dev:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools wheel

      # 🔹 AUTENTICAÇÃO SIMPLES (PAT)
      - name: Deploy to Databricks (DEV)
        run: databricks bundle deploy --target dev --var="user=${{ github.actor }}"
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_AUTH_TYPE: pat